# Generated by Django 2.1 on 2018-10-21 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0015_auto_20181021_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_sessions', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(default='none', max_length=250)),
                ('trainer_id', models.CharField(default='none', max_length=250)),
                ('total_sessions', models.IntegerField(default=0)),
                ('workout_name', models.CharField(max_length=250)),
                ('status', models.CharField(default='available', max_length=250)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
        migrations.AddField(
            model_name='availablesession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.Session'),
        ),
    ]
