# Generated by Django 2.1 on 2018-10-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-order']},
        ),
        migrations.AlterModelTable(
            name='session',
            table='Session',
        ),
    ]
