# Generated by Django 2.1 on 2018-10-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_availablesession_previous_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablesession',
            name='available_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='availablesession',
            name='previous_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
