# Generated by Django 2.1 on 2018-10-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_auto_20181022_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='total_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
