# Generated by Django 2.1 on 2018-10-22 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_auto_20181022_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availablesession',
            name='previous_sessions',
        ),
    ]
