# Generated by Django 2.1 on 2018-10-23 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0007_remove_availablesession_previous_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablesession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availablesession', to='session.Session'),
        ),
    ]
