# Generated by Django 2.1 on 2018-09-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_auto_20180917_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='trainerprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='trainerprofile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
