# Generated by Django 2.1 on 2018-10-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_auto_20180917_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='stripe_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
