# Generated by Django 2.1 on 2018-10-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_trainerprofile_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='sessions',
            field=models.IntegerField(default=0),
        ),
    ]
