# Generated by Django 2.1 on 2018-10-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0012_auto_20181022_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
