# Generated by Django 2.1 on 2018-11-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0013_auto_20181023_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
    ]
