# Generated by Django 2.1 on 2018-11-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0014_workout_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='stripe_product_id',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
