# Generated by Django 2.1 on 2018-11-05 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0015_workout_stripe_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='stripe_product_id',
        ),
    ]
