# Generated by Django 2.1 on 2018-11-08 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0017_auto_20181108_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerprofile',
            name='stripe_id',
        ),
        migrations.RemoveField(
            model_name='trainerprofile',
            name='stripe_pub_key',
        ),
        migrations.RemoveField(
            model_name='trainerprofile',
            name='stripe_secret_key',
        ),
    ]
