# Generated by Django 2.1 on 2018-11-08 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym', '0018_auto_20181108_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeDetail',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=100, null=True)),
                ('stripe_id', models.CharField(max_length=200, null=True)),
                ('stripe_pub_key', models.CharField(max_length=200, null=True)),
                ('stripe_secret_key', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
