# Generated by Django 2.1 on 2018-11-08 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stripedetail',
            table='StripeDetail',
        ),
    ]
