# Generated by Django 2.1 on 2018-11-10 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_details', '0002_auto_20181108_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_entity_address_city', models.CharField(max_length=100)),
                ('legal_entity_address_line1', models.CharField(max_length=100)),
                ('legal_entity_address_postal_code', models.CharField(max_length=100)),
                ('legal_entity_business_name', models.CharField(max_length=200)),
                ('legal_entity_typebusiness_tax_id', models.CharField(max_length=200)),
                ('companies_house_registration_number_CRN', models.CharField(max_length=200)),
                ('legal_entity_personal_address_city', models.CharField(max_length=100)),
                ('legal_entity_personal_address_line1', models.CharField(max_length=100)),
                ('legal_entity_personal_address_postal_code', models.CharField(max_length=100)),
                ('tos_acceptance_date', models.DateTimeField(auto_now_add=True)),
                ('tos_acceptance_ip', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'StripeCompany',
            },
        ),
        migrations.CreateModel(
            name='ExternalAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_account_new_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100, null=True)),
                ('object', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('account_holder_name', models.CharField(max_length=100)),
                ('account_holder_type', models.CharField(max_length=100)),
                ('routing_number', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'StripeExternalAccount',
            },
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_entity_address_city', models.CharField(max_length=100)),
                ('legal_entity_address_line1', models.CharField(max_length=100)),
                ('legal_entity_address_postal_code', models.CharField(max_length=100)),
                ('legal_entity_dob_day', models.PositiveIntegerField()),
                ('legal_entity_dob_month', models.PositiveIntegerField()),
                ('legal_entity_dob_year', models.PositiveIntegerField()),
                ('legal_entity_first_name', models.CharField(max_length=100)),
                ('legal_entity_last_name', models.CharField(max_length=100)),
                ('tos_acceptance_date', models.DateTimeField(auto_now_add=True)),
                ('tos_acceptance_ip', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'StripeIndividual',
            },
        ),
        migrations.AddField(
            model_name='stripedetail',
            name='legal_entity_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='stripe_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stripe_details.StripeDetail'),
        ),
        migrations.AddField(
            model_name='externalaccount',
            name='stripe_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stripe_details.StripeDetail'),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stripe_details.StripeDetail'),
        ),
    ]
