# Generated by Django 2.1 on 2018-11-10 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_details', '0003_auto_20181110_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='stripe_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stripe_details.StripeDetail'),
        ),
    ]
