# Generated by Django 2.1 on 2018-11-10 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_details', '0004_auto_20181110_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='stripe_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stripe_details.StripeDetail'),
        ),
        migrations.AlterField(
            model_name='externalaccount',
            name='stripe_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stripe_details.StripeDetail'),
        ),
    ]
