# Generated by Django 2.1 on 2018-11-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_details', '0007_remove_externalaccount_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripedetail',
            name='stripe_token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
