# Generated by Django 2.1 on 2018-11-14 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_details', '0008_stripedetail_stripe_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripedetail',
            name='stripe_token',
        ),
    ]
