# Generated by Django 2.1 on 2018-10-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20181005_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billingName',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
