# Generated by Django 2.1 on 2018-10-05 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_billingname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billingName',
        ),
    ]
