# Generated by Django 2.1 on 2018-10-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_order_billingname'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sessions',
            field=models.IntegerField(default=0),
        ),
    ]
