# Generated by Django 2.1 on 2018-10-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_orderitem_workout_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='client_id',
            field=models.CharField(default='none', max_length=250),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='trainer_id',
            field=models.CharField(default='none', max_length=250),
        ),
    ]
