# Generated by Django 2.1 on 2018-10-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20181019_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='client_name',
        ),
    ]
