# Generated by Django 2.1 on 2018-10-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20181019_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='net',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='GBP Order Net Total'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='GBP Order Gross Total'),
        ),
    ]
