# Generated by Django 2.1 on 2018-10-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20181021_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Stripe Fee'),
        ),
    ]
