# Generated by Django 2.1 on 2018-10-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_stripe_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='net',
            new_name='net_fee',
        ),
        migrations.AddField(
            model_name='order',
            name='platform_fee',
            field=models.IntegerField(default=2),
        ),
    ]
