# Generated by Django 2.1 on 2018-10-21 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20181021_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='net_fee',
            new_name='net_pay',
        ),
    ]
