# Generated by Django 2.1 on 2018-10-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20181021_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='trainer',
        ),
        migrations.AddField(
            model_name='order',
            name='trainer_name',
            field=models.CharField(default='none', max_length=250),
        ),
    ]
