# Generated by Django 2.1 on 2018-11-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20181023_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='emailAddress',
        ),
        migrations.AddField(
            model_name='order',
            name='client_email',
            field=models.EmailField(blank=True, max_length=250, verbose_name='Client Email'),
        ),
        migrations.AddField(
            model_name='order',
            name='trainer_email',
            field=models.EmailField(blank=True, max_length=250, verbose_name='Trainer Email'),
        ),
    ]
