# Generated by Django 2.1 on 2018-11-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20181103_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
    ]
