# Generated by Django 2.1 on 2018-11-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_order_stripe_plan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_customer_id',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
