# Generated by Django 2.1 on 2018-11-14 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_order_stripe_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_customer_id',
        ),
    ]
