# Generated by Django 2.1 on 2018-11-17 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_remove_order_stripe_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_product_id',
            new_name='stripe_product_name',
        ),
    ]
