# Generated by Django 2.1 on 2018-11-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_auto_20181117_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_subscription_id',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
