# Generated by Django 2.1 on 2018-11-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_order_stripe_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_invoice_id',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
